"""add active profile mode

Revision ID: 08da64ae2f07
Revises: ceecee7fb9e0
Create Date: 2026-04-26 15:29:48.112528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08da64ae2f07'
down_revision: Union[str, Sequence[str], None] = 'ceecee7fb9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "active_profile_mode",
            sa.String(length=20),
            nullable=False,
            server_default="solo",
        ),
    )

    op.alter_column("users", "active_profile_mode", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_profile_mode')
    # ### end Alembic commands ###
