"""create recipe ratings table

Revision ID: 4f031032609d
Revises: 22228458a3f2
Create Date: 2026-04-12 19:50:42.603896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f031032609d'
down_revision: Union[str, Sequence[str], None] = '22228458a3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_item_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_item_id'], ['meal_plan_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ratings_meal_plan_item_id'), 'recipe_ratings', ['meal_plan_item_id'], unique=False)
    op.create_index(op.f('ix_recipe_ratings_user_id'), 'recipe_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ratings_user_id'), table_name='recipe_ratings')
    op.drop_index(op.f('ix_recipe_ratings_meal_plan_item_id'), table_name='recipe_ratings')
    op.drop_table('recipe_ratings')
    # ### end Alembic commands ###
