"""add family_id to meal plans

Revision ID: b8c596175462
Revises: 08da64ae2f07
Create Date: 2026-04-27 14:59:29.599640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c596175462'
down_revision: Union[str, Sequence[str], None] = '08da64ae2f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('family_id', sa.Integer(), nullable=True))
    op.alter_column('meal_plans', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_meal_plans_family_id'), 'meal_plans', ['family_id'], unique=False)
    op.create_foreign_key(None, 'meal_plans', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_plans', type_='foreignkey')
    op.drop_index(op.f('ix_meal_plans_family_id'), table_name='meal_plans')
    op.alter_column('meal_plans', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('meal_plans', 'family_id')
    # ### end Alembic commands ###
