"""create user preferences table

Revision ID: f0bfedfa024d
Revises: 86995a5264be
Create Date: 2026-04-10 13:40:16.097257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0bfedfa024d'
down_revision: Union[str, Sequence[str], None] = '86995a5264be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disliked_products', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('favorite_products', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_products', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_cuisines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooking_difficulty', sa.String(length=50), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
